import type { Product } from "@/store/useCartStore";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Apple iPhone 14 Pro",
    price: 1099,
    originalPrice: 1199,
    rating: 4.8,
    reviews: 12450,
    description:
      "The latest iPhone with A16 Bionic chip, Dynamic Island, and ProMotion display.",
    images: [
      "https://www.apple.com/newsroom/images/product/iphone/standard/Apple_iPhone-14-Pro_Deep-Purple-Availability-220907.jpg",
      "https://www.apple.com/newsroom/images/product/iphone/standard/Apple_iPhone-14-Pro_Silver-Availability-220907.jpg",
    ],
    sizes: [],
    colors: [
      { name: "Deep Purple", hex: "#4B0082" },
      { name: "Silver", hex: "#C0C0C0" },
      { name: "Gold", hex: "#FFD700" },
    ],
    features: ["48MP Camera", "A16 Bionic", "ProMotion Display", "Face ID"],
    specifications: {
      Processor: "A16 Bionic",
      Display: "6.1-inch Super Retina XDR",
      Storage: "128GB",
    },
    inStock: true,
    category: "Electronics",
    color: "Deep Purple",
    size: "",
  },
  {
    id: "2",
    name: "Nike Air Max 270",
    price: 160,
    originalPrice: 190,
    rating: 4.6,
    reviews: 8921,
    description:
      "Comfortable lifestyle sneakers with a large Air unit for maximum cushioning.",
    images: [
      "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/air-max-270-mens-shoes-KkLcGR.png",
    ],
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: [
      { name: "Black/White", hex: "#000000" },
      { name: "Red", hex: "#FF0000" },
    ],
    features: ["Lightweight", "Breathable", "Max Air Cushioning"],
    specifications: {
      Material: "Mesh & Synthetic",
      Sole: "Rubber",
    },
    inStock: true,
    category: "Shoes",
    color: "Black/White",
    size: "10",
  },
  {
    id: "3",
    name: "Samsung Galaxy S23 Ultra",
    price: 1199,
    originalPrice: 1299,
    rating: 4.7,
    reviews: 10345,
    description: "Samsung’s flagship smartphone with 200MP camera and S Pen.",
    images: [
      "https://images.samsung.com/is/image/samsung/p6pim/levant/2302/gallery/levant-galaxy-s23-ultra-s918-sm-s918bzkamea-thumb-534695123",
      "https://images.samsung.com/is/image/samsung/p6pim/levant/2302/gallery/levant-galaxy-s23-ultra-s918-sm-s918bzkamea-534695125",
    ],
    sizes: [],
    colors: [
      { name: "Phantom Black", hex: "#0A0A0A" },
      { name: "Green", hex: "#006400" },
    ],
    features: ["200MP Camera", "Snapdragon 8 Gen 2", "S Pen"],
    specifications: {
      Processor: "Snapdragon 8 Gen 2",
      Display: "6.8-inch QHD+",
      Storage: "256GB",
    },
    inStock: true,
    category: "Electronics",
    color: "Phantom Black",
    size: "",
  },
  {
    id: "4",
    name: "Sony WH-1000XM5 Headphones",
    price: 399,
    originalPrice: 449,
    rating: 4.9,
    reviews: 14231,
    description: "Industry-leading noise canceling wireless headphones.",
    images: ["https://m.media-amazon.com/images/I/61vJtKbAssL._AC_SL1500_.jpg"],
    sizes: [],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Silver", hex: "#C0C0C0" },
    ],
    features: ["Noise Cancelling", "30-hour Battery", "Hi-Res Audio"],
    specifications: {
      Connectivity: "Bluetooth 5.2",
      Battery: "30 hours",
    },
    inStock: true,
    category: "Electronics",
    color: "Black",
    size: "",
  },
  {
    id: "5",
    name: "Adidas Ultraboost 22",
    price: 180,
    originalPrice: 220,
    rating: 4.7,
    reviews: 7531,
    description:
      "High-performance running shoes with responsive Boost cushioning.",
    images: [
      "https://assets.adidas.com/images/w_600,f_auto,q_auto/4f61b60e7e08441a8965adf200f77912_9366/Ultraboost_22_Shoes_Black_GX3066_01_standard.jpg",
    ],
    sizes: ["7", "8", "9", "10", "11"],
    colors: [
      { name: "Core Black", hex: "#000000" },
      { name: "Cloud White", hex: "#FFFFFF" },
    ],
    features: ["Boost Midsole", "Primeknit Upper", "Durable Outsole"],
    specifications: {
      Material: "Textile & Synthetic",
      Sole: "Rubber",
    },
    inStock: true,
    category: "Shoes",
    color: "Core Black",
    size: "9",
  },
  {
    id: "6",
    name: "MacBook Pro 14-inch (M2 Pro)",
    price: 1999,
    originalPrice: 2199,
    rating: 4.9,
    reviews: 4521,
    description:
      "Powerful MacBook Pro with M2 Pro chip and Liquid Retina XDR display.",
    images: [
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp14-silver-select-202301?wid=2000&hei=2000&fmt=jpeg&qlt=90&.v=1671304673229",
    ],
    sizes: [],
    colors: [
      { name: "Space Gray", hex: "#2E2E2E" },
      { name: "Silver", hex: "#C0C0C0" },
    ],
    features: ["M2 Pro Chip", "XDR Display", "All-day Battery"],
    specifications: {
      Processor: "Apple M2 Pro",
      RAM: "16GB",
      Storage: "512GB SSD",
    },
    inStock: true,
    category: "Electronics",
    color: "Space Gray",
    size: "",
  },
  {
    id: "7",
    name: "Levi’s 501 Original Jeans",
    price: 89,
    originalPrice: 110,
    rating: 4.5,
    reviews: 2314,
    description: "Classic straight fit jeans with iconic Levi’s design.",
    images: ["https://lsco.scene7.com/is/image/lsco/005010194-front-pdp"],
    sizes: ["30", "32", "34", "36", "38"],
    colors: [{ name: "Dark Blue", hex: "#00008B" }],
    features: ["Durable Denim", "Classic Fit"],
    specifications: {
      Material: "100% Cotton",
      Fit: "Straight",
    },
    inStock: true,
    category: "Clothing",
    color: "Dark Blue",
    size: "32",
  },
  {
    id: "8",
    name: "Apple Watch Series 8",
    price: 399,
    originalPrice: 449,
    rating: 4.6,
    reviews: 5213,
    description:
      "Smartwatch with health monitoring, always-on display, and crash detection.",
    images: [
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MQKQ3_VW_34FR+watch-45-alum-starlight-nc-s8_VW_34FR_WF_CO?wid=2000&hei=2000&fmt=jpeg&qlt=90&.v=1661471340499",
    ],
    sizes: ["41mm", "45mm"],
    colors: [
      { name: "Midnight", hex: "#191970" },
      { name: "Starlight", hex: "#F8F8FF" },
    ],
    features: ["ECG", "Blood Oxygen", "Crash Detection"],
    specifications: {
      Display: "Always-On Retina",
      Processor: "S8 Chip",
    },
    inStock: true,
    category: "Electronics",
    color: "Midnight",
    size: "45mm",
  },
  {
    id: "9",
    name: "Canon EOS R6 Mark II",
    price: 2499,
    originalPrice: 2699,
    rating: 4.8,
    reviews: 3120,
    description:
      "Professional mirrorless camera with 24.2MP sensor and 4K 60p video.",
    images: ["https://m.media-amazon.com/images/I/81WcCgWqvFL._AC_SL1500_.jpg"],
    sizes: [],
    colors: [{ name: "Black", hex: "#000000" }],
    features: ["24.2MP Full-Frame", "4K 60p", "Dual Pixel AF II"],
    specifications: {
      Sensor: "Full-Frame CMOS",
      Processor: "DIGIC X",
    },
    inStock: true,
    category: "Electronics",
    color: "Black",
    size: "",
  },
  {
    id: "10",
    name: "PlayStation 5 Console",
    price: 499,
    originalPrice: 549,
    rating: 4.9,
    reviews: 18340,
    description:
      "Next-gen gaming console with ultra-fast SSD and immersive gameplay.",
    images: ["https://m.media-amazon.com/images/I/619BkvKW35L._AC_SL1500_.jpg"],
    sizes: [],
    colors: [{ name: "White/Black", hex: "#FFFFFF" }],
    features: ["4K Gaming", "Ray Tracing", "DualSense Controller"],
    specifications: {
      Storage: "825GB SSD",
      Processor: "AMD Zen 2",
    },
    inStock: true,
    category: "Electronics",
    color: "White/Black",
    size: "",
  },
];
