import type { Product } from "@/store/useCartStore";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Apple iPhone 14 Pro",
    price: 1099,
    originalPrice: 1199,
    rating: 4.8,
    reviews: 12450,
    description:
      "The latest iPhone with A16 Bionic chip, Dynamic Island, and ProMotion display.",
    images: [
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-pro-finish-select-202209-6-1inch-deeppurple?wid=5120&hei=2880&fmt=jpeg&qlt=90&.v=1663703841494",
    ],
    sizes: [],
    colors: [
      { name: "Deep Purple", hex: "#4B0082" },
      { name: "Silver", hex: "#C0C0C0" },
      { name: "Gold", hex: "#FFD700" },
    ],
    features: ["48MP Camera", "A16 Bionic", "ProMotion Display", "Face ID"],
    specifications: {
      Processor: "A16 Bionic",
      Display: "6.1-inch Super Retina XDR",
      Storage: "128GB",
    },
    inStock: true,
    category: "Electronics",
    color: "Deep Purple",
    size: "",
  },
  {
    id: "2",
    name: "Nike Air Max 270",
    price: 160,
    originalPrice: 190,
    rating: 4.6,
    reviews: 8921,
    description:
      "Comfortable lifestyle sneakers with a large Air unit for maximum cushioning.",
    images: [
      "https://static.nike.com/a/images/t_default/7b4e458b-b9cb-4f1c-8bcb-502d65b9d9aa/air-max-270-mens-shoes-KkLcGR.png",
    ],
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: [
      { name: "Black/White", hex: "#000000" },
      { name: "Red", hex: "#FF0000" },
    ],
    features: ["Lightweight", "Breathable", "Max Air Cushioning"],
    specifications: {
      Material: "Mesh & Synthetic",
      Sole: "Rubber",
    },
    inStock: true,
    category: "Shoes",
    color: "Black/White",
    size: "10",
  },
  {
    id: "3",
    name: "Samsung Galaxy S23 Ultra",
    price: 1199,
    originalPrice: 1299,
    rating: 4.7,
    reviews: 10345,
    description: "Samsung’s flagship smartphone with 200MP camera and S Pen.",
    images: [
      "https://i.ebayimg.com/images/g/nCEAAOSwXJlmd7is/s-l500.jpg",
      "https://cdn1.ozone.ru/s3/multimedia-1-x/7628606205.jpg",
    ],
    sizes: [],
    colors: [
      { name: "Phantom Black", hex: "#0A0A0A" },
      { name: "Green", hex: "#006400" },
    ],
    features: ["200MP Camera", "Snapdragon 8 Gen 2", "S Pen"],
    specifications: {
      Processor: "Snapdragon 8 Gen 2",
      Display: "6.8-inch QHD+",
      Storage: "256GB",
    },
    inStock: true,
    category: "Electronics",
    color: "Phantom Black",
    size: "",
  },
  {
    id: "4",
    name: "Sony WH-1000XM5 Headphones",
    price: 399,
    originalPrice: 449,
    rating: 4.9,
    reviews: 14231,
    description: "Industry-leading noise canceling wireless headphones.",
    images: [
      "https://avatars.mds.yandex.net/i?id=0e9e7de0639aa5fa61d9925e158f13d6_l-6235762-images-thumbs&n=13",
    ],
    sizes: [],
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Silver", hex: "#C0C0C0" },
    ],
    features: ["Noise Cancelling", "30-hour Battery", "Hi-Res Audio"],
    specifications: {
      Connectivity: "Bluetooth 5.2",
      Battery: "30 hours",
    },
    inStock: true,
    category: "Electronics",
    color: "Black",
    size: "",
  },
  {
    id: "5",
    name: "Adidas Ultraboost 22",
    price: 180,
    originalPrice: 220,
    rating: 4.7,
    reviews: 7531,
    description:
      "High-performance running shoes with responsive Boost cushioning.",
    images: ["https://kedred.ru/wp-content/uploads/2024/01/11-19-584x480.jpg"],
    sizes: ["7", "8", "9", "10", "11"],
    colors: [
      { name: "Core Black", hex: "#000000" },
      { name: "Cloud White", hex: "#FFFFFF" },
    ],
    features: ["Boost Midsole", "Primeknit Upper", "Durable Outsole"],
    specifications: {
      Material: "Textile & Synthetic",
      Sole: "Rubber",
    },
    inStock: true,
    category: "Shoes",
    color: "Core Black",
    size: "9",
  },
  {
    id: "6",
    name: "MacBook Pro 14-inch (M2 Pro)",
    price: 1999,
    originalPrice: 2199,
    rating: 4.9,
    reviews: 4521,
    description:
      "Powerful MacBook Pro with M2 Pro chip and Liquid Retina XDR display.",
    images: ["https://i.ytimg.com/vi/j1NDOdUTuH4/maxresdefault.jpg"],
    sizes: [],
    colors: [
      { name: "Space Gray", hex: "#2E2E2E" },
      { name: "Silver", hex: "#C0C0C0" },
    ],
    features: ["M2 Pro Chip", "XDR Display", "All-day Battery"],
    specifications: {
      Processor: "Apple M2 Pro",
      RAM: "16GB",
      Storage: "512GB SSD",
    },
    inStock: true,
    category: "Electronics",
    color: "Space Gray",
    size: "",
  },
  {
    id: "7",
    name: "Levi’s 501 Original Jeans",
    price: 89,
    originalPrice: 110,
    rating: 4.5,
    reviews: 2314,
    description: "Classic straight fit jeans with iconic Levi’s design.",
    images: ["https://i.ebayimg.com/images/g/50sAAOSwIDBb23Dz/s-l400.jpg"],
    sizes: ["30", "32", "34", "36", "38"],
    colors: [{ name: "Dark Blue", hex: "#00008B" }],
    features: ["Durable Denim", "Classic Fit"],
    specifications: {
      Material: "100% Cotton",
      Fit: "Straight",
    },
    inStock: true,
    category: "Clothing",
    color: "Dark Blue",
    size: "32",
  },
  {
    id: "8",
    name: "Apple Watch Series 8",
    price: 399,
    originalPrice: 449,
    rating: 4.6,
    reviews: 5213,
    description:
      "Smartwatch with health monitoring, always-on display, and crash detection.",
    images: ["https://images.uzum.uz/cgs4s6ng49devoadrbvg/original.jpg"],
    sizes: ["41mm", "45mm"],
    colors: [
      { name: "Midnight", hex: "#191970" },
      { name: "Starlight", hex: "#F8F8FF" },
    ],
    features: ["ECG", "Blood Oxygen", "Crash Detection"],
    specifications: {
      Display: "Always-On Retina",
      Processor: "S8 Chip",
    },
    inStock: true,
    category: "Electronics",
    color: "Midnight",
    size: "45mm",
  },
  {
    id: "9",
    name: "Canon EOS R6 Mark II",
    price: 2499,
    originalPrice: 2699,
    rating: 4.8,
    reviews: 3120,
    description:
      "Professional mirrorless camera with 24.2MP sensor and 4K 60p video.",
    images: [
      "https://s.yimg.com/ny/api/res/1.2/SUIVZrdDr9jywlAD5OsDRw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTk2MDtoPTU3OTtjZj13ZWJw/https://s.yimg.com/os/creatr-uploaded-images/2022-11/38bbcff0-5a66-11ed-bfcf-2e98a133667e",
    ],
    sizes: [],
    colors: [{ name: "Black", hex: "#000000" }],
    features: ["24.2MP Full-Frame", "4K 60p", "Dual Pixel AF II"],
    specifications: {
      Sensor: "Full-Frame CMOS",
      Processor: "DIGIC X",
    },
    inStock: true,
    category: "Electronics",
    color: "Black",
    size: "",
  },
  {
    id: "10",
    name: "PlayStation 5 Console",
    price: 499,
    originalPrice: 549,
    rating: 4.9,
    reviews: 18340,
    description:
      "Next-gen gaming console with ultra-fast SSD and immersive gameplay.",
    images: [
      "https://main-cdn.sbermegamarket.ru/big2/hlr-system/645/890/130/929/173/8/100071148396b2.jpeg",
    ],
    sizes: [],
    colors: [{ name: "White/Black", hex: "#FFFFFF" }],
    features: ["4K Gaming", "Ray Tracing", "DualSense Controller"],
    specifications: {
      Storage: "825GB SSD",
      Processor: "AMD Zen 2",
    },
    inStock: true,
    category: "Electronics",
    color: "White/Black",
    size: "",
  },
];
